@extends('app.layout.iframe')

@section('content')
  <div class="container-fluid">
    <div class="row import-csv">
      <div class="col-xs-6">
        <form action="{{ route( 'import_locations' )  }}" method="POST" accept-charset="UTF-8" enctype="multipart/form-data">
          <input type="hidden" name="_token" value="{{ csrf_token() }}">

          <input type="file" name="csv_file">

          <button type="submit">Send it</button>
        </form>
      </div>
      <div class="col-xs-6">
        <div class="info-box">
          <i>When importing from a <b>.CSV</b> file that has been generated by other "Store Locator" applications, you will need to match each field to their corresponding group.</i>
        </div>
      </div>
    </div>
    <hr>
    <div class="row">
      <form action="{{ route( 'import_retailers' )  }}" method="POST" accept-charset="UTF-8">
        @foreach ($keys as $value)
          <div class="col-xs-3 py-2">
            <h6>{{ucfirst($value)}}</h6>
            <select name="[]" class="form-control-sm pt-2">
              @foreach ($values as $value)
                <option value="{{$value}}">{{$value}}</option>
              @endforeach
            </select>
          </div>
        @endforeach
        <button type="submit">Send it</button>
      </form>
    </div>
    <hr>
    <div class="row">

    </div>
  </div>
@stop

@section('js')

@stop
